# Generated by Django 4.0.6 on 2023-09-04 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolvedExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_id', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='problems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line1_equation', models.CharField(max_length=100, null=True)),
                ('line2_equation', models.CharField(max_length=100, null=True)),
                ('intersection_point', models.CharField(max_length=255, null=True)),
                ('line_equation', models.CharField(max_length=255)),
                ('area', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('height', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('base', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('y_intersection', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('x_intersection', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('x_when_y_zero', models.FloatField(blank=True, null=True)),
                ('y_when_x_zero', models.FloatField(blank=True, null=True)),
                ('point1_x', models.IntegerField(default=0)),
                ('point1_y', models.IntegerField(default=0)),
                ('point2_x', models.IntegerField(default=0)),
                ('point2_y', models.IntegerField(default=0)),
                ('slope', models.IntegerField(default=0)),
                ('y_intercept', models.IntegerField(default=0)),
                ('equation', models.CharField(default='', max_length=100)),
                ('a_fl', models.FloatField(blank=True, null=True)),
                ('b_fl', models.FloatField(blank=True, null=True)),
                ('c_fl', models.FloatField(blank=True, null=True)),
                ('option', models.CharField(max_length=1)),
                ('result', models.IntegerField(null=True)),
                ('correct_answer_fl', models.FloatField(blank=True, null=True)),
                ('equation_text', models.CharField(default='Default Equation', max_length=255)),
                ('correct_answer', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('a', models.IntegerField(default=0)),
                ('b', models.IntegerField(default=0)),
                ('c', models.IntegerField(default=0)),
                ('d', models.IntegerField(default=0)),
                ('e', models.IntegerField(default=0)),
                ('f', models.IntegerField(default=0)),
                ('g', models.IntegerField(default=0)),
                ('solution_x', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('solution_y', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('equation1', models.CharField(max_length=255)),
                ('equation2', models.CharField(max_length=255)),
                ('problem_str', models.TextField(null=True)),
                ('solution', models.TextField(null=True)),
                ('solved_by', models.ManyToManyField(blank=True, related_name='solved_problems', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
